site_name: DSA Problem Solutions
repo_url: https://github.com/sachin141097/DSAProblemSolutions
theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
    - social
    - search: null

extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/sachin141097
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/sachinrana1410/
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/sachinr73588136
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  
nav:
- Overview:
  - Overview/index.md
  - Arrays:
    - Arrays/index.md
    - 1. Right Rotate Array: Arrays/rotate_array_189/README.md
    - 2. Largest Element in Array: Arrays/largest_element_in_array/README.md
    - 3. Left Rotate Array: Arrays/left_rotate_array/README.md


copyright: |
  &copy; 2024 <a href="https://github.com/sachin141097"  target="_blank" rel="noopener">Sachin Rana</a>