site_name: DSA Problem Solutions
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  
nav:
- Overview:
  - Overview/index.md
  - Arrays:
    - Arrays/index.md
    - 1. Right Rotate Array: Arrays/rotate_array_189/README.md
    - 2. Largest Element in Array: Arrays/largest_element_in_array/README.md
    - 3. Left Rotate Array: Arrays/left_rotate_array/README.md


copyright: |
  &copy; 2024 <a href="https://github.com/sachin141097"  target="_blank" rel="noopener">Sachin Rana</a>